import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

/**
 * 元数据，有助于SEO优化
 */
export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    // 子路由的SEO的title将会被填充到此处
    // 试试访问http://localhost:3000/blog/1
    // 观察其标题变化
    template: "%s | Next.js App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
